apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-management-deploy
  labels:
    app: course-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-management
  template:
    metadata:
      labels:
        app: course-management
    spec:
      containers:
      - name: course-management-service
        image: dinalsenadheera/course-management-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URI
          value: "mongodb+srv://Dinal:mxm81632@cluster0.bzuizxa.mongodb.net/Course_Management_Service?retryWrites=true&w=majority&appName=Cluster0"
        - name: PORT
          value: "3001"
        - name: NODE_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: course-management-svc
spec:
  type: NodePort
  selector:
    app: course-management
  ports:
  - name: course-management-port
    protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 31000
