apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-deploy
  labels:
    app: local-cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-cms
  template:
    metadata:
      labels:
        app: local-cms
    spec:
      containers:
      - name: app
        image: local/cms:v1
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: local-cms-svc
spec:
  type: NodePort
  selector:
    app: local-cms
  ports:
  - name: local-cms-port
    protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 31000