apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-management-deploy
  namespace: ctse-microservices
  labels:
    app: course-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-management
  template:
    metadata:
      labels:
        app: course-management
    spec:
      containers:
      - name: course-management-service
        image: dinalsenadheera/ctse-assignment-cms:latest
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: cms-mongo-uri
        - name: PORT
          value: "3001"
        - name: NODE_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: course-management-svc
  namespace: ctse-microservices
spec:
  type: ClusterIP
  selector:
    app: course-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
